### ISSUE TITLE
Console logs errors when emoji is in channel name

### ISSUE THREAD

**Issue by DaCaemboe** [hyp3rd/telegram-discord-bridge#48] opened 2023-12-06 11:36 UTC
**Describe the bug**
Console logs errors when emoji is in channel name. Seems to be having encoding character errors.

**To Reproduce**
1. Put an emoji in the channel name.
2. Start the script
3. See error

**Expected behavior**
No errors

**Additional context**

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python310\lib\logging\__init__.py", line 1101, in emit
    stream.write(msg + self.terminator)
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f9ff' in position 65: character maps to <undefined>
Call stack:
  File "C:\Python310\telegram-discord-bridge-main\forwarder.py", line 581, in <module>
    controller(dispatcher=event_dispatcher, event_loop=asyncio.new_event_loop() ,boot=__start, stop=__stop, background=__background)
  File "C:\Python310\telegram-discord-bridge-main\forwarder.py", line 541, in controller
    start_bridge(dispatcher=dispatcher)
  File "C:\Python310\telegram-discord-bridge-main\forwarder.py", line 360, in start_bridge
    event_loop.run_forever()
  File "C:\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Python310\lib\asyncio\base_events.py", line 1873, in _run_once
    handle._run()
  File "C:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python310\telegram-discord-bridge-main\bridge\core.py", line 77, in start
    logger.info("Registered TG channel '%s' with ID %s with Discord channel config %s",
Message: "Registered TG channel '%s' with ID %s with Discord channel config %s"
Arguments: ('🧿 Testchannel, {'discord_channel_id': 1181817652536820064, ' strip_off_links': False, 'mention_everyone': False, 'forward_everything': True, 'forward_hashtags': [{'name': '#tester', 'override_mention_everyone': True}], 'excluded_hashtags': [], 'mention_override': {}, 'roles': []})
```

**Comment by hyp3rd** [comment] 2023-12-14 17:03
This will be fixed at the next merge

**Comment by hyp3rd** [comment] 2023-12-18 08:31
<img width="1327" alt="Screenshot 2023-12-18 at 09 28 24" src="https://github.com/hyp3rd/telegram-discord-bridge/assets/62474964/9eb577f6-a56d-4613-a063-d94a8609f0c6">

On Unix like machine the issue never existed. I can't reproduce it on my mac, but please update your code to the latest changes and try again.

**Closed by hyp3rd** 2023-12-18 08:31 UTC
